# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contador.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 51, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 151, 61))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.btnDecrementar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrementar.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.btnDecrementar.setObjectName("btnDecrementar")
        self.btnAcrescentar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAcrescentar.setGeometry(QtCore.QRect(190, 120, 75, 23))
        self.btnAcrescentar.setObjectName("btnAcrescentar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Valor:"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.btnDecrementar.setText(_translate("MainWindow", "Decrementar"))
        self.btnAcrescentar.setText(_translate("MainWindow", "Acrescentar"))
